[project]
name = "champ-suits"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.11"

dependencies = [
    "numpy",
    "pandas",
    "streamlit",
]

[dependency-groups]
dev = [
    "ruff>=0.15.16",
]

[project.scripts]
champ-suits = "main:main"
